- name: Adding Compose user[s] when/if needed
  user: 
    name: "{{ item.login_name }}" 
    state: present 
    comment: "{{ item.full_name }}" 
    shell: /bin/bash
    append: yes
    groups: mock
  with_items: "{{ kojid_compose_user_list }}"
  when: kojid_compose_user_list is defined
  loop_control:
    label: "{{ item.login_name }}"
  tags:
    - users
- name: Importing Compose user[s] ssh pub keys
  authorized_key: 
    user: "{{ item.0.login_name }}" 
    key: "{{ item.1 }}"
  with_subelements:
   - "{{ kojid_compose_user_list }}"
   - ssh_pub_key
  when: kojid_compose_user_list is defined
  loop_control:
    label: "{{ item.0.login_name }}"
  tags:
    - users

- name: Giving sudo access for Compose user[s] when needed
  template: 
    src: templates/sudofile.j2 
    dest: /etc/sudoers.d/{{ item.login_name }} 
    mode: 0440 
    owner: root 
    group: root
  with_items: "{{ kojid_compose_user_list }}"
  loop_control:
    label: "{{ item.login_name }}"
  when: kojid_compose_user_list is defined and item.sudo_right
  tags:
    - users

- name: make directories for the compose mounts
  file:
    path: "{{ item.target }}"
    state: directory
  with_items:
    - "{{ kojid_compose_mounts }}"
  when: kojid_compose_mounts is defined

- name: mount the compose mounts
  mount:
    fstype: nfs
    src: "{{ item.source }}"
    path: "{{ item.target }}"
    opts: "{{ item.opts }}"
    state: mounted
  with_items:
    - "{{ kojid_compose_mounts }}"
  when: kojid_compose_mounts is defined
