- name: kvm host role 
  import_role:
    name: kvm-host

- name: Install the Image tooling on the compose boxes
  yum:
    name:
      - imagefactory
      - "imagefactory-plugins-*"
      - pykickstart
      - nfs-utils
      - pykickstart
      - oz
    state: latest
  notify: 
    - restart_kojid

- name: Template the oz config 
  template:
    src: oz.cfg.j2
    dest: /etc/oz/oz.cfg
  notify:
    - restart_kojid
