---

- name: install kerberos packages
  package:
    name:
      - krb5-workstation
    state: installed

- name: install signing service keytabs on kernel builders
  copy:
    src: "{{ item }}"
    dest: "/etc/pesign.keytab"
  with_first_found:
    - "{{ pkistore }}/koji/{{ inventory_hostname }}.keytab"
    - "{{ pkistore }}/koji/autopesign-{{ inventory_hostname }}.keytab"
    - "{{ pkistore }}/koji/centos-stream.keytab"
