---

- include_tasks: pki.yml

- name: Add the buildtools repo if needed
  template:
    src: buildtools.repo.j2
    dest: /etc/yum.repos.d/buildtools.repo
  when: kojid_buildtools_repo
  tags:
    - repo

- name: Adding repo gpg key if needed
  copy: 
    src: files/RPM-GPG-KEY-CentOS-Infra 
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Infra
  when: kojid_buildtools_repo and kojid_buildtools_repo_gpgcheck  
  tags:
    - repo

- name: Ensuring koji pkgs are installed
  yum:
    name: 
      - koji-builder
      - mock
      - createrepo_c
    state: latest

- block:
    - name: Importing needed keytab for kojid if using kerberos auth
      copy:
        src: "{{ pkistore }}/koji/{{ koji_auth_keytab }}"
        dest: "/etc/kojid/{{ koji_auth_keytab }}"
      notify: restart_kojid

  when: koji_auth_kerberos

- name: Adding/updating more pkgs if we need buildtools repo
  yum:
    name:
      - dnf
      - dnf-plugins-core
      - gpgme
      - rpm
    state: latest
  when: kojid_buildtools_repo

- name: Configuring kojid
  template:
    src: kojid.conf.j2
    dest: /etc/kojid/kojid.conf
  notify: restart_kojid

- name: Ensuring kojid is started and enabled
  service:
    name: kojid
    state: started
    enabled: True


- name: set a static route for get if needed
  shell: "nmcli con mod \"{{ kojid_nmcli_con }}\" +ipv4.routes \"{{ item.scm_server }} {{ item.gateway }}\" && nmcli con up \"{{ kojid_nmcli_con }}\" "
  with_items:
    - "{{ kojid_add_route_to_scm }}"
  when: kojid_add_route_to_scm is defined
  tags:
    - routes


# Some packages need a default route defined (not necessarily reachable)
# See: https://bugs.ruby-lang.org/issues/13864
# We can define one that points at localhost to stop any outbound tracffic
# but have a route defined
- name: get the current default route
  command: "/usr/sbin/ip route show 0.0.0.0/0"
  register: default_route
  tags:
    - route

- name: delete the default route if it is not localhost
  command: "/usr/sbin/ip route del default"
  when: not '127.0.0.1' in default_route.stdout and kojid_set_default_nullroute
  register: delete_default_route
  failed_when:
    - delete_default_route.rc !=0
    - '"No such process" not in delete_default_route.stderr'
  tags:
    - route

- name: add the null default route
  command: "/usr/sbin/ip route add default via 127.0.0.1"
  when: kojid_set_default_nullroute and not (delete_default_route is skipped)
  tags:
    - route

- block:
    - name: Configuring zabbix agent
      include_role:
        name: zabbix-server
        tasks_from: agent_config
      vars:
        zabbix_templates: "{{ zabbix_kojid_templates }}"
        zabbix_groups: "{{ zabbix_kojid_groups }}"
  delegate_to: "{{ zabbix_api_srv }}"  
  tags:
    - monitoring
  when: zabbix_api_srv is defined

- name: Setting up nfs mount
  include_tasks: nfs.yml
  when: koji_nfs_mount
  tags:
    - nfs

- name: Including compose task when needed
  include_tasks: compose.yml
  when: kojid_compose_user
  tags:
    - compose

- name: Including runroot tasks when needed
  include_tasks: runroot.yml
  when: kojid_runroot_builder
  tags:
    - runroot

- name: Including image builder tasks when needed
  include_tasks: image.yml
  when: kojid_image_builder
  tags:
    - image
