- name: Ensuring we have some nfs pkgs installed
  yum:
    name: nfs-utils
    state: installed
 
- name: koji store mount point exist
  file:
    path: "{{ koji_mountpoint }}"
    state: directory

- name: Ensuring we have nfs koji store mounted
  mount:
    path: "{{ koji_mountpoint }}"
    src: "{{ koji_nfs_path }}"
    fstype: nfs
    state: mounted

- name: Workaround for some hard-coded path in koji
  file:
    src: "{{ koji_mountpoint}}/koji"
    dest: /mnt/koji
    state: link

- block:
    - name: Ensuring addtional volume[s] is/are defined
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.dest }}"
        fstype: nfs
        state: present
      register: additional_mountpoints
      with_items: "{{ koji_nfs_additional_mountpoints }}"
      loop_control:
        label: "{{ item.dest }}"
      tags:
        - nfs

    - name: Ensuring addtional volume[s] is/are mounted
      ansible.posix.mount:
        src: "{{ item.item.src }}"
        path: "{{ item.item.dest }}"
        fstype: nfs
        state: mounted
      with_items: "{{ additional_mountpoints.results }}"
      when: item.changed
      loop_control:
        label: "{{ item.item.dest }}"
      tags:
        - nfs
  when:
    - koji_nfs_mount
    - koji_nfs_mount_multi

