- name: Ensuring we have koji builder plugins installed
  yum:
    name: koji-builder-plugins
    state: installed
  notify:
    - restart_kojid

- name: Template the runroot config 
  template:
    src: runroot.conf.j2
    dest: /etc/kojid/plugins/runroot.conf
  notify:
    - restart_kojid
